language: scala

scala:
  - 2.11.12
  - 2.12.10

jdk:
  - openjdk8
  - openjdk11

branches:
  except:
    - /^wip-.*$/

env:
  - TRAVIS_NODE_VERSION="10.9.0" SCALAJS_VERSION="0.6.30"
  # - TRAVIS_NODE_VERSION="10.9.0" SCALAJS_VERSION="1.0.0-M8"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - which node
# small tricks to enable faster builds

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.nvm

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  # Your normal script
  - sbt ++$TRAVIS_SCALA_VERSION squantsJVM/compile squantsJS/compile squantsJS/fastOptJS
  - if [[ $TRAVIS_SCALA_VERSION == "2.11.12" ]]; then sbt ++$TRAVIS_SCALA_VERSION squantsNative/compile; fi;
  - if [[ $SCALAJS_VERSION == "0.6.30" ]]; then sbt ++$TRAVIS_SCALA_VERSION squantsJS/test; fi;
  - sbt ++$TRAVIS_SCALA_VERSION squantsJVM/test
