name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v3
      - name: Set up JDK 1.8
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 1.8
      - name: Run tests
        run: |
          csbt +squantsJVM/compile +squantsJS/compile
          csbt squantsNative/compile
          csbt +squantsJVM/test +squantsJS/test
